/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'on-secondary-fixed-variant': '#3a485b',
        'primary-fixed-dim': '#bec6e0',
        'surface-dim': '#d8dadc',
        secondary: '#515f74',
        'tertiary-fixed-dim': '#4cd7f6',
        tertiary: '#000000',
        'on-tertiary': '#ffffff',
        'on-secondary-container': '#57657a',
        primary: '#06B6D4',
        'on-primary-fixed': '#131b2e',
        'on-error': '#ffffff',
        'on-secondary-fixed': '#0d1c2e',
        'on-tertiary-fixed': '#001f26',
        'error-container': '#ffdad6',
        'surface-container': '#eceef0',
        'on-secondary': '#ffffff',
        'on-tertiary-fixed-variant': '#004e5c',
        'on-surface': '#0F172A',
        'inverse-primary': '#bec6e0',
        'secondary-fixed-dim': '#b9c7df',
        'on-error-container': '#93000a',
        'on-tertiary-container': '#0090a9',
        'secondary-fixed': '#d5e3fc',
        'inverse-surface': '#2d3133',
        'surface-container-high': '#e6e8ea',
        background: '#F8FAFC',
        'surface-container-highest': '#e0e3e5',
        'surface-variant': '#e0e3e5',
        'on-dark': '#F8FAFC',
        'tertiary-container': '#001f26',
        'primary-container': '#131b2e',
        'tertiary-fixed': '#acedff',
        'primary-fixed': '#dae2fd',
        error: '#ba1a1a',
        'dark-section': '#0F172A',
        'surface-tint': '#565e74',
        'on-surface-variant': '#334155',
        'secondary-container': '#d5e3fc',
        'surface-container-lowest': '#ffffff',
        'accent-glow': 'rgba(6, 182, 212, 0.15)',
        'on-primary-fixed-variant': '#3f465c',
        'on-primary': '#ffffff',
        'on-background': '#0F172A',
        surface: '#F1F5F9',
        'on-primary-container': '#7c839b',
        'inverse-on-surface': '#eff1f3',
        'surface-container-low': '#f2f4f6',
        outline: '#76777d',
        'outline-variant': '#c6c6cd',
        'surface-bright': '#f7f9fb',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      spacing: {
        'stack-lg': '160px',
        'stack-md': '64px',
        'margin-x': '80px',
        'container-max': '1280px',
        'stack-sm': '16px',
        gutter: '48px',
        'section-gap': '120px',
        'margin-desktop': '64px',
      },
      maxWidth: {
        'container-max': '1280px',
      },
      fontFamily: {
        'body-md': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'display-lg': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '1.6', letterSpacing: '0em', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '1.4', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.75', letterSpacing: '0em', fontWeight: '400' }],
        'display-lg': ['48px', { lineHeight: '1.2', letterSpacing: '-0.03em', fontWeight: '800' }],
        'headline-lg': ['32px', { lineHeight: '1.3', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-md': ['13px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '600' }],
      },
    },
  },
  plugins: [require('@tailwindcss/forms'), require('@tailwindcss/container-queries')],
}
